name: CI-CD Pipeline
on:
push:
branches:
- main
jobs:
build_and_push:
steps:
- uses: actions/checkout@v3
- uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
- uses: docker/build-push-action@v4
with:
push: true
tags: pavanij2005/jpapp:v2
deploy:
needs: build_and_push
steps:
- uses: appleboy/ssh-action@v1.0.3
with:
host: ${{ secrets.SERVER_IP }}
username: pavanij2005
key: ${{ secrets.SERVER_SSH_KEY }}
script: |
cd jpapp
docker-compose pull
docker-compose up -d
